spring:
  datasource:
    url: ${vcap.services.customers-db.credentials.jdbcUrl}&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db
    username: ${vcap.services.customers-db.credentials.username:root}
    password: ${vcap.services.customers-db.credentials.password:petclinic}

username: ${/p-bosh/cf-63fa4a3a591f8d52eac6/locket-db-credentials.username}
password: ${/p-bosh/cf-63fa4a3a591f8d52eac6/locket-db-credentials.password}